# Generated by Django 5.1.4 on 2025-01-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredient',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='menu_item',
            new_name='name',
        ),
    ]
